set -g history-limit 10000
set -g default-terminal "screen-256color"
set -sg escape-time 10

source-file ~/.tmux/colorscheme.conf
source-file ~/.tmux/keybindings.conf
if-shell "[ -f ~/.tmux/local.conf ]" "source-file ~/.tmux/local.conf"

if-shell -F '#{==:#{default-shell},}' "set -g default-shell /usr/bin/fish"
