complete -f -c ohh -n '__fish_prog_needs_command ohh' -l basedir -d "directory containing ohh data"
complete -f -c ohh -n '__fish_prog_needs_command ohh' -l version -d "shows version and exit"
complete -f -c ohh -n '__fish_prog_needs_command ohh' -a start -d "start ohh"
complete -f -c ohh -n '__fish_prog_needs_command ohh' -a stop -d "stop ohh"
complete -f -c ohh -n '__fish_prog_needs_command ohh' -a login -d "login to ohh"
complete -f -c ohh -n '__fish_prog_needs_command ohh' -a status -d "display ohh status"
complete -f -c ohh -n '__fish_prog_using_command start' -l office -d "start office session"
complete -f -c ohh -n '__fish_prog_using_command start' -l foreground -d "start ohh in the foreground"
complete -f -c ohh -n '__fish_prog_using_command stop' -l office -d "stop office session"
