complete -f -c venv -n '__fish_prog_needs_command' -l help -d "shows help"
complete -f -c venv -n '__fish_prog_needs_command' -a activate -d "activates venv for current directory (default)"
complete -f -c venv -n '__fish_prog_needs_command' -a path -d "shows the path of the current venv"
complete -f -c venv -n '__fish_prog_needs_command' -a create -d "creates a new venv"
complete -f -c venv -n '__fish_prog_needs_command' -a destroy -d "destroys the current venv"
