alias g='git'
alias gst='git status'
alias glg='git log --stat --color'
alias glgga='git log --graph --decorate --all'

abbr -a ga='git add'
abbr -a gco='git checkout'
abbr -a gcm='git checkout master'
abbr -a gd='git diff'
abbr -a gdc='git diff --cached'
abbr -a gc='git commit'
abbr -a gp='git push'
abbr -a gl='git pull'
abbr -a gb='git branch'
abbr -a gm='git merge'
