fundle plugin 'tuvistavie/fish-fastdir'
fundle plugin 'tuvistavie/fish-completion-helpers'
fundle plugin 'tuvistavie/fish-ssh-agent'
fundle plugin 'tuvistavie/fish-theme-afowler'
fundle plugin 'tuvistavie/fish-gcalcli'
fundle plugin 'tuvistavie/fish-nvm'
fundle plugin 'joehillen/to-fish'
